# Generated by Django 6.0.5 on 2026-05-27 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_demand', models.CharField(help_text='Current demand value in MW', max_length=50)),
                ('yesterday_demand', models.CharField(help_text="Yesterday's demand value in MW", max_length=50)),
                ('time_block', models.CharField(blank=True, help_text='The time block string extracted from the site', max_length=50, null=True)),
                ('date', models.DateField(blank=True, help_text='The date extracted from the website', null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the data was captured')),
            ],
            options={
                'db_table': 'mh_demand_data',
                'ordering': ['-captured_at'],
            },
        ),
    ]
